### ISSUE TITLE
typo in README.md

### ISSUE THREAD

**Issue by Julien1138** [testmonitor/eloquent-incrementable#3]
Hi,

Thanks for the very usefull package !
I just want to point a typo in the example code for group usage, in the "Usage" section of the README.md file:
`protected $incrementableGroups = ['project_id'];`
should be
`protected $incrementableGroup = ['project_id'];` (No 's' to groups)

This made me think this package was not working...

**Comment by stefanius** [comment]
Hi Julien1138,

Thank you for using our package and reporting this issue so we can improve the package. We updated the readme and the solved the issue.

Regards,
Stephan.
